### ISSUE TITLE
El directorio node_modules no se sube a git, se ha de incluir en el .gitignore

### ISSUE THREAD

**Issue by vicenlu** [Spanioulis/Sprint-5#1]
Con el package.json es suficiente, ya quien clone el proyecto hará npm install e instalará todas las dependencias.

Más info: https://stackoverflow.com/questions/50701496/why-can-not-i-upload-the-node-modules-file-into-github-repository

https://github.com/Spanioulis/Sprint-5/blob/febf8f53d51b62585598081a113bf56e3bdcec9d/node_modules/.bin/tsc#L2

**Comment by Spanioulis** [comment]
Gracias Luis:

Hago los cambios/mejoras de todas las issues ;)

Justo iba a entregar el Sprint-6 ahora y he visto que en Create React App la carpeta "/node_modules" ya viene por defecto  en .gitignore
